### ISSUE TITLE
It would be lovely to have some docs on how to run the backend

### ISSUE THREAD

**Issue by wdoug** [andrewMacmurray/realworld-hasura#42]
I see some scripts in the `backend/package.json` file, but I'm a bit confused on how I should run them. Also, do I need to install. Also, I'm assuming I need to install the [Hasura CLI](https://hasura.io/docs/latest/graphql/core/hasura-cli/install-hasura-cli/) first?

**Comment by andrewMacmurray** [comment]
Hey @wdoug, thanks for this - yea the running instructions are a bit messy at the moment. I've moved those scripts to the root now + added `hasura-cli` as a dev dependency.

Have a look and see if the instructions are a bit clearer now? Happy for you to make a PR if you have any suggestions
